using System.Globalization;
using AutoMapper;
using MassTransit;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Petalaka.Account.Contract.Repository.Entities;
using Petalaka.Account.Contract.Repository.Interface;
using Petalaka.Account.Contract.Repository.ModelViews.RequestModels;
using Petalaka.Account.Contract.Repository.ModelViews.ResponseModels;
using Petalaka.Account.Contract.Service.Interface;
using Petalaka.Account.Core.ExceptionCustom;
using Petalaka.Account.Core.Utils;
using Petalaka.Account.Service.Events.AccountEvent;
using Petalaka.Service.Shared.RabbitMQ.Events.Interfaces;

namespace Petalaka.Account.Service.Services;

public class AccountService : IAccountService
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IPublishEndpoint _publishEndpoint;
    private readonly ITokenService _tokenService;
    private readonly IMapper _mapper; 
    
    public AccountService
    (
        UserManager<ApplicationUser> userManager, 
        IUnitOfWork unitOfWork,
        IPublishEndpoint publishEndpoint,
        IMapper mapper,
        ITokenService tokenService
        )
    {
        _userManager = userManager;
        _unitOfWork = unitOfWork;
        _publishEndpoint = publishEndpoint;
        _mapper = mapper;
        _tokenService = tokenService;
    }
    
    public async Task<IEnumerable<ApplicationUser>> GetAllUsers()
    {
        return await _unitOfWork.ApplicationUserRepository.AsQueryable().ToListAsync();
    }

    /// <summary>
    /// Check if user is already confirmed email or not and check if email otp is correct and not expired then set email confirmed to true
    /// </summary>
    /// <param name="request"></param>
    /// <exception cref="CoreException"></exception>
    public async Task ConfirmEmail(ConfirmEmailRequestModel request)
    {
        ApplicationUser user = await _userManager.FindByEmailAsync(request.Email);
        if(user == null)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "User not found");
        }
        if(user.EmailConfirmed)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email is already confirmed");
        }
        if(user.EmailOtp != request.EmailOtp)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email OTP is incorrect");
        }
        //Check if email otp is expired in 5 minutes as unix timestamp
        if(String.CompareOrdinal(user.EmailOtpExpiration, TimeStampHelper.GenerateUnixTimeStamp()) < 0 )
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email OTP is expired");
        }
        //Set email confirmed to true and remove current email otp
        user.EmailConfirmed = true;
        user.EmailOtp = null;
        await _userManager.UpdateAsync(user);
    }

    public async Task SendEmailOtp(ResendEmailConfirmationRequestModel request)
    {
        ApplicationUser user = await _userManager.FindByEmailAsync(request.Email);
        if(user == null)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "User not found");
        }
        
        //generate new email otp and email otp expiration
        user.EmailOtp = OtpGenerator.GenerateOtp();
        user.EmailOtpExpiration = TimeStampHelper.GenerateUnixTimeStampOtp();
        await _userManager.UpdateAsync(user);
        
        //publish email otp to rabbitmq
        IEmailOtpEvent message = new EmailOtpEvent
        {
            Email = user.Email,
            EmailOtp = user.EmailOtp
        };  
        await _publishEndpoint.Publish(message);
    }
    
    public async Task ChangePassword(string email, ChangePasswordRequestModel request)
    {
        ApplicationUser user = await _userManager.FindByEmailAsync(email);
        if(user == null)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "User not found");
        }

        if (!user.EmailConfirmed)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email is not confirmed");
        }
        
        //Get salt from database and hash current password
        string salt = await _unitOfWork.ApplicationUserRepository.GetUserSalt(p => p.Email == email);
        string hashedPassword = PasswordHasher.HashPassword(request.CurrentPassword, salt);
        //check if hashedPassword with salt is equal to passwordHash in database by identity (hashedPassword in database is generated by identity - 2 times hash)
        bool checkPassword = await _userManager.CheckPasswordAsync(user, hashedPassword);
        
        if (!checkPassword)
        {
            throw new CoreException(StatusCodes.Status401Unauthorized, "Current password is incorrect");
        }
        
        //Generate new salt and hash new password with salt
        string newSalt = PasswordHasher.GenerateSalt();
        string newHashedPassword = PasswordHasher.HashPassword(request.NewPassword, newSalt);
        
        //Change password
        IdentityResult result = await _userManager.ChangePasswordAsync(user, hashedPassword, newHashedPassword);
        if(!result.Succeeded)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, result.Errors.First().Description);
        }
        
        //Update salt and save salt to database
        user.Salt = newSalt;
        await _userManager.UpdateAsync(user);
    }

    public async Task<ConfirmForgotPasswordResponseModel> ForgotPassword(ForgotPasswordRequestModel request)
    {
        ApplicationUser user = await _userManager.FindByEmailAsync(request.Email);
        if(user == null)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "User not found");
        }

        if (!user.EmailConfirmed)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email is not confirmed");
        } 
        
        if(user.EmailOtp != request.EmailOtp)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "OTP is incorrect");
        }
        //Check if forgot password otp is expired in 5 minutes as unix timestamp
        if(String.CompareOrdinal(user.EmailOtpExpiration, TimeStampHelper.GenerateUnixTimeStamp()) < 0 )
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "OTP is expired");
        }
        //Set forgot password otp to null
        user.EmailOtp = null;
        await _userManager.UpdateAsync(user);
        
        var token = await _tokenService.GenerateTokens(user);
        return new ConfirmForgotPasswordResponseModel
        {
            AccessToken = token.accessToken,
            RefreshToken = token.refreshToken,
        };
    }
    
    
    public async Task NewPasswordForgot(string email, NewPasswordRequestModel request)
    {
        ApplicationUser user = await _userManager.FindByEmailAsync(email);
        
        if(user == null)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "User not found");
        }
        
        if (!user.EmailConfirmed)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email is not confirmed");
        }
        
        //Generate new salt and hash new password with salt
        string newSalt = PasswordHasher.GenerateSalt();
        string newHashedPassword = PasswordHasher.HashPassword(request.NewPassword, newSalt);

        //Change password using reset password token
        var token = await _userManager.GeneratePasswordResetTokenAsync(user);
        IdentityResult result = await _userManager.ResetPasswordAsync(user, token, newHashedPassword);
        if(!result.Succeeded)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, result.Errors.First().Description);
        }
        
        //Update salt and save salt to database
        user.Salt = newSalt;
        await _userManager.UpdateAsync(user);
    }

    public async Task ForgotPasswordV2(ForgotPasswordV2RequestModel request)
    {
        ApplicationUser user = await _userManager.FindByEmailAsync(request.Email);
        if(user == null)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "User not found");
        }
        
        if (!user.EmailConfirmed)
        {
            throw new CoreException(StatusCodes.Status400BadRequest, "Email is not confirmed");
        }
        //Generate reset password token and expired timestamp
        string resetPasswordToken = await _userManager.GeneratePasswordResetTokenAsync(user);
        string timeStamp = TimeStampHelper.GenerateCustomUnixTimeStamp(0, 10, 0).ToString();
        
        //publish email event to rabbitmq with reset password token and expired timestamp
        IForgotPasswordEventV2 message = new ForgotPasswordEventV2()
        {
            Email = user.Email,
            ResetPasswordToken = resetPasswordToken,
            ExpiredTimeStamp = timeStamp
        };  
        await _publishEndpoint.Publish(message);
    }
}