version: '3.4'

services:
  petalaka.account.api:
    image: ${DOCKER_REGISTRY-}petalakaaccountapi
    build:
      context: .
      dockerfile: Petalaka.Account.API/Dockerfile
    networks:
      - petalaka-accountservice-network
      - petalaka.rabbitmq_network
    restart: 
        on-failure
    depends_on: 
      - petalaka.account.sqlserver

  petalaka.account.sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "StrongDatabasePassword!@#123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - petalaka-accountservice-network
    volumes:
      - petalaka-account-sqlserver:/var/opt/mssql
  petalaka.rabbitmq:
    image: rabbitmq:management
    container_name: petalaka.rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbitmqsecretpassword123
    networks:
      - petalaka.rabbitmq_network
networks:
  petalaka-accountservice-network: 
    driver: bridge
  petalaka.rabbitmq_network:
    driver: bridge
volumes:
  petalaka-account-sqlserver: